name: ASPSearch
channels: 
  - conda-forge
  - potassco
  - anaconda
  - potassco/label/dev
dependencies:
  - python>=3,<4
  - clingo=5.5
  - python-clingox=1.0
  - jupyter=1.0
  - clingraph
  - graphviz
  - telingo=2.1
  - pip


